---
image:
  name: hashicorp/terraform
  entrypoint:
    - /usr/bin/env

cache:
  paths:
    - terraform/.terraform

stages:
  - lint
  - test
  - package
  - plan
  - apply
  - destroy

yamllint:
  image: sdesbure/yamllint
  stage: lint
  script:
    - yamllint .

fmt-check:
  stage: lint
  script:
    - terraform fmt -recursive -check

tflint:
  stage: lint
  image:
    name: wata727/tflint
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd terraform
    - tflint .

eslint:
  stage: lint
  image: willhallonline/eslint-standard:alpine
  script:
    - eslint ./lambda-function

dockerfile-lint:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile

validate:
  stage: test
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform version
    - terraform validate

test:
  image:
    name: registry.gitlab.com/who-docker/docker-terratest
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - cp -r $CI_PROJECT_DIR /go/src/terratest
    - cd /go/src/terratest/test
    - dep ensure -v
    - go test -v
  only:
    - test

container:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

container-release:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

package:
  stage: package
  image: registry.gitlab.com/who-docker/aws-cli:latest
  script:
    - zip hello.zip ./lambda-function/
    - aws s3 cp hello.zip s3://wh-terraform-hello/$CI_COMMIT_TAG/hello.zip
  only:
    - tags

plan:
  stage: plan
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform plan -var 's3_key=$CI_COMMIT_TAG/hello.zip' -out out.tfplan
  artifacts:
    expire_in: 8 weeks
    paths:
      - terraform/out.tfplan
  only:
    - tags

apply:
  stage: apply
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform apply -input=false out.tfplan
  when: manual
  only:
    - tags

destroy:
  stage: destroy
  script:
    - cd terraform
    - echo $tfc_credentials > /root/.terraformrc
    - terraform init
    - terraform destroy -auto-approve
  when: manual
  only:
    - tags
