---
image:
  name: hashicorp/terraform
  entrypoint:
    - /usr/bin/env

cache:
  paths:
    - terraform/.terraform

stages:
  - lint
  - test
  - plan
  - apply
  - destroy

yamllint:
  image: sdesbure/yamllint
  stage: lint
  script:
    - yamllint .

fmt-check:
  stage: lint
  script:
    - terraform fmt -recursive -check

tflint:
  stage: lint
  image:
    name: wata727/tflint
    entrypoint: ["/bin/sh", "-c"]
  script:
    - cd terraform
    - tflint .

validate:
  stage: test
  cache:
    policy: push
  script:
    - cd terraform/
    - echo $tfc_credentials > terraform.rc
    - terraform init
    - terraform version
    - terraform validate

test:
  image:
    name: registry.gitlab.com/who-docker/docker-terratest
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  script:
    - cp -r $CI_PROJECT_DIR /go/src/terratest
    - cd /go/src/terratest/test
    - dep ensure -v
    - go test -v
  only:
    - test

plan:
  stage: plan
  script:
    - cd terraform
    - echo $tfc_credentials > terraform.rc
    - terraform plan -out out.tfplan
  artifacts:
    expire_in: 8 weeks
    paths:
      - out.tfplan

apply:
  stage: apply
  script:
    - cd terraform
    - echo $tfc_credentials > terraform.rc
    - terraform apply -input=false out.tfplan
  when: manual
  only:
    - tags
    - master

destroy:
  stage: destroy
  script:
    - cd terraform
    - echo $tfc_credentials > terraform.rc
    - terraform destroy -auto-approve
  when: manual
